/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'
import type { ThreeElements } from '@react-three/fiber'
import * as THREE from 'three'

type Props = ThreeElements['group'] & {
  shader_material: THREE.ShaderMaterial
}

export default function Character({ shader_material, ...props }: Props) {
  const { nodes, materials } = useGLTF('/models/hologram/Robocat.glb')

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes['Node-Mesh'] as THREE.Mesh).geometry}
        material={materials.mat13}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes['Node-Mesh_1'] as THREE.Mesh).geometry}
        material={materials.mat16}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes['Node-Mesh_2'] as THREE.Mesh).geometry}
        material={materials.mat19}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes['Node-Mesh_3'] as THREE.Mesh).geometry}
        material={materials.mat17}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes['Node-Mesh_4'] as THREE.Mesh).geometry}
        material={materials.mat23}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes['Node-Mesh_5'] as THREE.Mesh).geometry}
        material={materials.mat21}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes['Node-Mesh_6'] as THREE.Mesh).geometry}
        material={shader_material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes['Node-Mesh_7'] as THREE.Mesh).geometry}
        material={materials.mat5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes['Node-Mesh_8'] as THREE.Mesh).geometry}
        material={materials.mat14}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes['Node-Mesh_9'] as THREE.Mesh).geometry}
        material={materials.mat12}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes['Node-Mesh_10'] as THREE.Mesh).geometry}
        material={materials.mat20}
      />
      <mesh
        castShadow
        receiveShadow
        // geometry={nodes['Node-Mesh_11'].geometry}
        position={[0.37, 0.02, 0.27]}
        rotation-x={Math.PI}
        material={shader_material}
      >
        <sphereGeometry args={[0.17, 32, 16, 0, Math.PI * 2, 0, Math.PI / 2]} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/hologram/Robocat.glb')
